#line 1 "D:/Dev/nome/compilerNome/lexer.cpp"

#line 3 "D:/Dev/nome/compilerNome/lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer nom_create_buffer
#define yy_delete_buffer nom_delete_buffer
#define yy_scan_buffer nom_scan_buffer
#define yy_scan_string nom_scan_string
#define yy_scan_bytes nom_scan_bytes
#define yy_init_buffer nom_init_buffer
#define yy_flush_buffer nom_flush_buffer
#define yy_load_buffer_state nom_load_buffer_state
#define yy_switch_to_buffer nom_switch_to_buffer
#define yypush_buffer_state nompush_buffer_state
#define yypop_buffer_state nompop_buffer_state
#define yyensure_buffer_stack nomensure_buffer_stack
#define yy_flex_debug nom_flex_debug
#define yyin nomin
#define yyleng nomleng
#define yylex nomlex
#define yylineno nomlineno
#define yyout nomout
#define yyrestart nomrestart
#define yytext nomtext
#define yywrap nomwrap
#define yyalloc nomalloc
#define yyrealloc nomrealloc
#define yyfree nomfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define nom_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer nom_create_buffer
#endif

#ifdef yy_delete_buffer
#define nom_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer nom_delete_buffer
#endif

#ifdef yy_scan_buffer
#define nom_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer nom_scan_buffer
#endif

#ifdef yy_scan_string
#define nom_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string nom_scan_string
#endif

#ifdef yy_scan_bytes
#define nom_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes nom_scan_bytes
#endif

#ifdef yy_init_buffer
#define nom_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer nom_init_buffer
#endif

#ifdef yy_flush_buffer
#define nom_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer nom_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define nom_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state nom_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define nom_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer nom_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define nompush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state nompush_buffer_state
#endif

#ifdef yypop_buffer_state
#define nompop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state nompop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define nomensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack nomensure_buffer_stack
#endif

#ifdef yylex
#define nomlex_ALREADY_DEFINED
#else
#define yylex nomlex
#endif

#ifdef yyrestart
#define nomrestart_ALREADY_DEFINED
#else
#define yyrestart nomrestart
#endif

#ifdef yylex_init
#define nomlex_init_ALREADY_DEFINED
#else
#define yylex_init nomlex_init
#endif

#ifdef yylex_init_extra
#define nomlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra nomlex_init_extra
#endif

#ifdef yylex_destroy
#define nomlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy nomlex_destroy
#endif

#ifdef yyget_debug
#define nomget_debug_ALREADY_DEFINED
#else
#define yyget_debug nomget_debug
#endif

#ifdef yyset_debug
#define nomset_debug_ALREADY_DEFINED
#else
#define yyset_debug nomset_debug
#endif

#ifdef yyget_extra
#define nomget_extra_ALREADY_DEFINED
#else
#define yyget_extra nomget_extra
#endif

#ifdef yyset_extra
#define nomset_extra_ALREADY_DEFINED
#else
#define yyset_extra nomset_extra
#endif

#ifdef yyget_in
#define nomget_in_ALREADY_DEFINED
#else
#define yyget_in nomget_in
#endif

#ifdef yyset_in
#define nomset_in_ALREADY_DEFINED
#else
#define yyset_in nomset_in
#endif

#ifdef yyget_out
#define nomget_out_ALREADY_DEFINED
#else
#define yyget_out nomget_out
#endif

#ifdef yyset_out
#define nomset_out_ALREADY_DEFINED
#else
#define yyset_out nomset_out
#endif

#ifdef yyget_leng
#define nomget_leng_ALREADY_DEFINED
#else
#define yyget_leng nomget_leng
#endif

#ifdef yyget_text
#define nomget_text_ALREADY_DEFINED
#else
#define yyget_text nomget_text
#endif

#ifdef yyget_lineno
#define nomget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno nomget_lineno
#endif

#ifdef yyset_lineno
#define nomset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno nomset_lineno
#endif

#ifdef yywrap
#define nomwrap_ALREADY_DEFINED
#else
#define yywrap nomwrap
#endif

#ifdef yyalloc
#define nomalloc_ALREADY_DEFINED
#else
#define yyalloc nomalloc
#endif

#ifdef yyrealloc
#define nomrealloc_ALREADY_DEFINED
#else
#define yyrealloc nomrealloc
#endif

#ifdef yyfree
#define nomfree_ALREADY_DEFINED
#else
#define yyfree nomfree
#endif

#ifdef yytext
#define nomtext_ALREADY_DEFINED
#else
#define yytext nomtext
#endif

#ifdef yyleng
#define nomleng_ALREADY_DEFINED
#else
#define yyleng nomleng
#endif

#ifdef yyin
#define nomin_ALREADY_DEFINED
#else
#define yyin nomin
#endif

#ifdef yyout
#define nomout_ALREADY_DEFINED
#else
#define yyout nomout
#endif

#ifdef yy_flex_debug
#define nom_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug nom_flex_debug
#endif

#ifdef yylineno
#define nomlineno_ALREADY_DEFINED
#else
#define yylineno nomlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define nomwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[517] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   99,   98,
       97,   13,   98,   95,   96,   98,   94,   16,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   82,   83,    5,    8,    5,
        7,   15,   14,   11,   12,   11,   97,    0,    1,    0,
       16,   94,   16,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,    0,    5,    6,    4,    0,    0,    0,

       16,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   31,   94,   94,   30,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   40,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,    0,    0,   17,   17,
       94,   94,   94,   94,   38,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   18,   41,   94,   94,   94,   94,
       94,   94,   45,   94,   94,   94,   94,   94,   89,   94,
       94,   94,   94,   94,   94,   32,   94,   94,   94,   94,

       94,   94,   94,   81,    0,    0,    0,   17,   17,   17,
       94,    2,   94,   94,   94,   94,   94,   94,   36,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   76,   94,   94,   84,   94,
       94,   94,   94,   94,   35,   94,   94,   94,   56,   94,
       94,   94,   87,   94,   94,   94,   24,    0,    0,    0,
        3,   94,   94,   94,   94,   52,   21,   94,   74,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   94,   49,   94,   94,   94,
       73,   43,   28,   94,   94,   94,   61,   25,   94,   94,
       94,   94,   47,    0,    0,    0,   23,   94,   94,   94,
       94,   94,   39,   94,   94,   94,   94,   94,   42,   94,
       94,   94,   94,   94,   94,   46,   94,   94,   94,   90,
       94,   94,   94,   94,   94,   94,   94,   86,   94,   94,
       94,   94,   94,   94,   94,   62,   94,   33,   94,   94,
        0,   93,    0,    0,   94,   94,   19,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   77,   94,   94,   85,
       94,   94,   94,   37,   94,   94,   94,   88,   94,   94,

       94,   94,   58,   94,   94,   94,   51,   94,   94,   94,
        0,    9,   94,   94,   94,   94,   94,   94,   53,   94,
       75,   94,   50,   94,   94,   44,   29,   94,   94,   94,
       94,   94,   48,   94,   94,   94,   94,   94,   94,   54,
       60,   10,   65,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   34,   94,   63,   94,
       94,   94,   94,   94,   26,   94,   94,   94,   20,   94,
       94,   94,   59,   94,   94,   57,   94,   94,   67,   94,
       71,   94,   78,   91,   94,   94,   94,   94,   94,   94,
       94,   94,   55,   94,   69,   80,   66,   94,   94,   64,

       94,   94,   94,   94,   94,   27,   94,   68,   72,   94,
       79,   94,   92,   70,   22,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    6,    1,    1,    1,    7,
        8,    9,   10,    1,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,    1,
        1,    1,    1,    1,   13,   14,   15,   16,   17,   14,
       14,   14,   14,   14,   14,   14,   18,   19,   20,   21,
       14,   22,   14,   14,   14,   14,   14,   23,   14,   14,
        1,    1,    1,    1,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   14,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,    1,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        4,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    4,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1
    } ;

static const flex_int16_t yy_base[529] =
    {   0,
        0,    0,   49,   50,  638,  637,   51,   52,  639,  642,
       58,  642,    0,  629,  642,   52,  625,   54,    0,  613,
      622,  585,   42,   37,  604,   34,   50,  591,  593,   54,
       56,   52,   51,   66,   57,  601,  642,    0,  642,  620,
      620,  642,  642,  642,  642,  608,  104,  112,  642,  614,
      113,    0,  613,  603,  608,  589,   61,  572,  580,  578,
      579,  581,  577,  579,  586,  571,  572,  584,  569,  571,
      569,  565,  559,   85,   90,  571,  574,  560,  559,   96,
      556,  557,  574,  555,  564,  567,   89,  566,  553,  568,
      554,  558,  550,  542,    0,  642,  642,  572,    0,  163,

      575,  573,  563,  547,  548,  547,  548,  544,  552,  536,
      538,  534,  546,  189,  541,  532,  543,  542,  532,  525,
      100,    0,  537,  535,  533,  524,  535,  521,  520,  529,
      522,  511,  529,  532,  520,    0,  528,  514,  525,  522,
      522,  506,  511,  510,  505,  517,  505,  117,    0,  232,
      525,  523,  498,  510,    0,  511,  506,  502,  508,  495,
      493,  491,  112,  105,  504,  114,  491,  493,  501,  122,
       72,   96,  105,  493,    0,    0,  497,  498,  486,  497,
      499,  494,    0,  485,  482,  493,  490,  485,    0,  474,
      480,  474,  471,  484,  483,    0,  478,  485,  469,  466,

      465,  477,  462,    0,  463,  480,  489,    0,  283,    0,
      485,    0,  457,  458,  457,  459,  467,  467,    0,  452,
      464,  118,  443,  451,  449,  450,  452,  460,  445,  447,
      445,  441,  109,  448,  451,  437,  436,  124,  135,  449,
      436,  438,  436,  433,  437,    0,  443,  433,    0,  437,
      428,  425,  424,  438,    0,  432,  422,  434,    0,  420,
      416,  433,    0,  424,  422,  421,    0,  452,  434,  439,
        0,  421,  413,  424,  421,    0,    0,  420,    0,  413,
      412,  413,  409,  417,  401,  413,  412,  411,  401,  394,
      145,  406,  404,  406,  392,  391,  400,  393,  382,  401,

      398,  398,  382,  387,  386,  384,    0,  392,  394,  371,
        0,    0,  389,  389,  379,  387,    0,    0,  382,  385,
      375,  387,    0,  360,  397,  387,    0,  364,  363,  394,
      378,  373,    0,  374,  369,  365,  358,  356,    0,  367,
      368,  356,  367,  369,  364,    0,  365,  362,  357,    0,
      346,  352,  344,  344,  323,  316,  328,    0,  288,  306,
      301,  300,  303,  297,  297,    0,  283,    0,  285,  280,
      271,  642,  302,  300,  281,  277,  305,  273,  274,  273,
      275,  283,  269,  281,  268,  272,    0,  277,  267,    0,
      261,  260,  274,    0,  268,  255,  272,    0,  263,  261,

      258,  259,    0,  238,  253,  254,    0,  245,  234,  247,
      259,  642,  246,  228,  239,  232,  243,  240,    0,  239,
        0,  228,    0,  236,  238,    0,  234,  234,  224,  228,
      231,  221,    0,  230,  228,  216,  225,  226,  213,    0,
        0,  642,    0,  222,  211,  205,  204,  235,  219,  201,
      210,  201,  202,  195,  195,  181,    0,  182,    0,  176,
      171,  169,  181,  171,    0,  170,  169,  165,  193,  161,
      165,  175,    0,  174,  175,    0,  166,  155,    0,  155,
        0,  154,  153,    0,  166,  148,  159,  163,  161,  160,
      159,  146,    0,  151,    0,    0,    0,  154,  143,    0,

      139,  138,  150,  139,  120,    0,  117,    0,    0,  105,
        0,   66,    0,    0,    0,  642,  334,  340,  346,   86,
      349,  355,  361,   79,  367,  369,  375,  381
    } ;

static const flex_int16_t yy_def[529] =
    {   0,
      516,    1,  517,  517,  518,  518,  519,  519,  516,  516,
      516,  516,  520,  516,  516,  516,  521,  516,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  516,  516,  522,  516,  522,
      516,  516,  516,  516,  516,  516,  516,  523,  516,  516,
      516,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  516,  522,  516,  516,  516,  524,  525,

      516,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  516,  516,  526,  527,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,

      521,  521,  521,  521,  516,  516,  516,  526,  527,  209,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  516,  516,  516,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,

      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  528,  516,  516,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      528,  516,  516,  516,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,

      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      516,  516,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  516,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,

      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,    0,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516
    } ;

static const flex_int16_t yy_nxt[694] =
    {   0,
       10,   11,   11,   11,   12,   13,   14,   15,   10,   16,
       17,   18,   19,   19,   19,   19,   20,   21,   19,   19,
       19,   19,   19,   10,   22,   23,   24,   25,   26,   27,
       28,   19,   29,   19,   19,   19,   30,   19,   31,   32,
       33,   34,   35,   19,   19,   19,   19,   19,   19,   36,
       37,   39,   39,   45,   45,   40,   40,   41,   41,   47,
       47,   47,   50,   51,   50,   51,   57,   46,   46,   60,
       58,   65,   61,   66,   68,   62,   79,   63,   73,   81,
       67,   76,   74,   59,  149,   77,   75,  105,   69,   82,
       80,   48,   83,   70,   84,   89,  237,   90,  106,   78,

       91,   85,   92,  515,   93,   47,   47,   47,   86,   87,
      238,   88,   99,   99,  139,   99,   99,   99,   99,   99,
       99,   99,   99,   50,   51,  123,  124,  125,  131,  140,
      126,  132,  180,  206,  207,   99,  222,  225,  228,  239,
      223,  240,  181,  241,  280,  226,  514,  234,  242,  292,
      293,  235,  229,  224,  513,  281,  298,  230,  512,  299,
      300,   99,   99,   99,   99,  236,   99,   99,   99,   99,
       99,   99,   99,   99,  100,  301,  511,  343,  510,  509,
      508,  507,  506,  505,  504,  503,   99,  344,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,

      490,  489,  488,  487,  469,  486,  485,  484,  483,  482,
      481,  480,   99,   99,  163,  164,  165,  479,  166,  167,
      478,  168,  477,  476,  475,  169,  474,  170,  171,  473,
      172,  173,   99,   99,  472,   99,   99,   99,   99,   99,
       99,   99,   99,  209,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,   99,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,   99,   99,   99,   99,  435,   99,   99,   99,   99,
       99,   99,   99,   99,  209,  434,  433,  432,  431,  430,

      429,  428,  427,  426,  425,  424,   99,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  377,  414,  413,  412,
      411,  372,  410,  409,  408,  407,  406,  405,  404,  403,
      402,  401,   99,   99,   38,   38,   38,   38,   38,   38,
       42,   42,   42,   42,   42,   42,   44,   44,   44,   44,
       44,   44,   52,   52,   52,   95,  400,  399,   95,   95,
       95,  100,  398,  100,  100,  100,  100,  150,  397,  150,
      150,  150,  150,  208,  208,  210,  396,  210,  210,  210,
      210,  371,  371,  371,  371,  371,  371,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  383,

      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  297,  296,
      295,  294,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  279,  278,  277,  276,  275,  274,  273,  272,

      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  233,
      232,  231,  227,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  179,  178,
      177,  176,  175,  174,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  101,  148,  147,  146,
      145,  144,  143,  142,  141,  138,  137,  136,  135,  134,

      133,  130,  129,  128,  127,  122,  121,  120,  119,  118,
      117,  116,  115,  114,  113,  112,  111,  110,  109,  108,
      107,  104,  103,  102,   53,  101,   98,   97,   96,   94,
       72,   71,   64,   56,   55,   54,   53,   49,  516,   43,
       43,    9,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516

    } ;

static const flex_int16_t yy_chk[694] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    7,    8,    3,    4,    3,    4,   11,
       11,   11,   16,   16,   18,   18,   23,    7,    8,   24,
       23,   26,   24,   26,   27,   24,   32,   24,   30,   33,
       26,   31,   30,   23,  524,   31,   30,   57,   27,   33,
       32,  520,   34,   27,   34,   35,  171,   35,   57,   31,

       35,   34,   35,  512,   35,   47,   47,   47,   34,   34,
      171,   34,   48,   48,   87,   48,   48,   48,   48,   48,
       48,   48,   48,   51,   51,   74,   74,   75,   80,   87,
       75,   80,  121,  148,  148,   48,  163,  164,  166,  172,
      163,  172,  121,  173,  222,  164,  510,  170,  173,  233,
      233,  170,  166,  163,  507,  222,  238,  166,  505,  238,
      239,   48,   48,  100,  100,  170,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  239,  504,  291,  503,  502,
      501,  499,  498,  494,  492,  491,  100,  291,  490,  489,
      488,  487,  486,  485,  483,  482,  480,  478,  477,  475,

      474,  472,  471,  470,  469,  468,  467,  466,  464,  463,
      462,  461,  100,  100,  114,  114,  114,  460,  114,  114,
      458,  114,  456,  455,  454,  114,  453,  114,  114,  452,
      114,  114,  150,  150,  451,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  450,  449,  448,  447,  446,  445,
      444,  439,  438,  437,  436,  150,  435,  434,  432,  431,
      430,  429,  428,  427,  425,  424,  422,  420,  418,  417,
      416,  415,  414,  413,  411,  410,  409,  408,  406,  405,
      404,  150,  150,  209,  209,  402,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  401,  400,  399,  397,  396,

      395,  393,  392,  391,  389,  388,  209,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  371,  370,  369,  367,  365,  364,  363,  362,  361,
      360,  359,  209,  209,  517,  517,  517,  517,  517,  517,
      518,  518,  518,  518,  518,  518,  519,  519,  519,  519,
      519,  519,  521,  521,  521,  522,  357,  356,  522,  522,
      522,  523,  355,  523,  523,  523,  523,  525,  354,  525,
      525,  525,  525,  526,  526,  527,  353,  527,  527,  527,
      527,  528,  528,  528,  528,  528,  528,  352,  351,  349,
      348,  347,  345,  344,  343,  342,  341,  340,  338,  337,

      336,  335,  334,  332,  331,  330,  329,  328,  326,  325,
      324,  322,  321,  320,  319,  316,  315,  314,  313,  310,
      309,  308,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  278,  275,
      274,  273,  272,  270,  269,  268,  266,  265,  264,  262,
      261,  260,  258,  257,  256,  254,  253,  252,  251,  250,
      248,  247,  245,  244,  243,  242,  241,  240,  237,  236,
      235,  234,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  221,  220,  218,  217,  216,  215,  214,  213,

      211,  207,  206,  205,  203,  202,  201,  200,  199,  198,
      197,  195,  194,  193,  192,  191,  190,  188,  187,  186,
      185,  184,  182,  181,  180,  179,  178,  177,  174,  169,
      168,  167,  165,  162,  161,  160,  159,  158,  157,  156,
      154,  153,  152,  151,  147,  146,  145,  144,  143,  142,
      141,  140,  139,  138,  137,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  123,  120,  119,
      118,  117,  116,  115,  113,  112,  111,  110,  109,  108,
      107,  106,  105,  104,  103,  102,  101,   98,   94,   93,
       92,   91,   90,   89,   88,   86,   85,   84,   83,   82,

       81,   79,   78,   77,   76,   73,   72,   71,   70,   69,
       68,   67,   66,   65,   64,   63,   62,   61,   60,   59,
       58,   56,   55,   54,   53,   50,   46,   41,   40,   36,
       29,   28,   25,   22,   21,   20,   17,   14,    9,    6,
        5,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[99] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compilerNome/lexer.l"
#line 3 "compilerNome/lexer.l"
#include <stdio.h>
#include <string.h>
#include <string>
#include "parser.hpp"
#include "newNOME/Session.h"

int nomcolumn = 0;
int numBegComments = 0;
#define YY_USER_ACTION nomlloc.first_line = nomlloc.last_line = nomlineno; \
    nomlloc.first_column = nomcolumn; nomlloc.last_column = nomcolumn + nomleng - 1; \
    nomcolumn += nomleng;

static int isatty(int) {return 0;}
#line 1072 "D:/Dev/nome/compilerNome/lexer.cpp"
#define YY_NO_UNISTD_H 1

#line 1075 "D:/Dev/nome/compilerNome/lexer.cpp"

#define INITIAL 0
#define MULTI_COMMENT 1
#define LINE_COMMENT 2
#define INSIDE_MACRO 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 28 "compilerNome/lexer.l"

#line 1297 "D:/Dev/nome/compilerNome/lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 517 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 642 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "compilerNome/lexer.l"
numBegComments++; BEGIN(MULTI_COMMENT);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "compilerNome/lexer.l"
numBegComments++; BEGIN(INSIDE_MACRO);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "compilerNome/lexer.l"
numBegComments++; BEGIN(INSIDE_MACRO);
	YY_BREAK


case 4:
YY_RULE_SETUP
#line 35 "compilerNome/lexer.l"
numBegComments--; if (numBegComments == 0){ BEGIN(INITIAL); };
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 "compilerNome/lexer.l"
// eat comment in chunks
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 "compilerNome/lexer.l"
numBegComments++;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "compilerNome/lexer.l"
// eat the lone star
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 39 "compilerNome/lexer.l"
;
	YY_BREAK


case 9:
YY_RULE_SETUP
#line 42 "compilerNome/lexer.l"
numBegComments--; if (numBegComments == 0){ BEGIN(INITIAL); };
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "compilerNome/lexer.l"
numBegComments--; if (numBegComments == 0){ BEGIN(INITIAL); };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "compilerNome/lexer.l"
;
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 45 "compilerNome/lexer.l"
;
	YY_BREAK

case 13:
YY_RULE_SETUP
#line 47 "compilerNome/lexer.l"
{ BEGIN(LINE_COMMENT); }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 48 "compilerNome/lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "compilerNome/lexer.l"
{ }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "compilerNome/lexer.l"
nomlval.string=nomtext; return NUMBER;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "compilerNome/lexer.l"
nomlval.string=strdup(nomtext); return BANK_EXPR;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "compilerNome/lexer.l"
return EXPR;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "compilerNome/lexer.l"
nomlval.intNumber = std::stoi(std::string(nomtext).substr (7)); return BSPLINE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "compilerNome/lexer.l"
nomlval.intNumber = std::stoi(std::string(nomtext).substr (10)); return END_BSPLINE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "compilerNome/lexer.l"
return CLOSED;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "compilerNome/lexer.l"
return MINIMIZETORSION;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "compilerNome/lexer.l"
return AZIMUTH;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "compilerNome/lexer.l"
return TWIST;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "compilerNome/lexer.l"
return SLICES;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "compilerNome/lexer.l"
return BEZIERCURVE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "compilerNome/lexer.l"
return END_BEZIERCURVE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "compilerNome/lexer.l"
return OFFSET;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "compilerNome/lexer.l"
return END_OFFSET;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "compilerNome/lexer.l"
return MIN;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "compilerNome/lexer.l"
return MAX;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "compilerNome/lexer.l"
return STEP;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "compilerNome/lexer.l"
return SURFACE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "compilerNome/lexer.l"
return END_SURFACE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "compilerNome/lexer.l"
return BEG_POINT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "compilerNome/lexer.l"
return COLOR;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "compilerNome/lexer.l"
return END_POINT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "compilerNome/lexer.l"
return BANK;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "compilerNome/lexer.l"
return END_BANK;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "compilerNome/lexer.l"
return SET;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "compilerNome/lexer.l"
return FACE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "compilerNome/lexer.l"
return END_FACE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "compilerNome/lexer.l"
return OBJECT;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "compilerNome/lexer.l"
return END_OBJECT;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "compilerNome/lexer.l"
return MESH;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "compilerNome/lexer.l"
return END_MESH;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "compilerNome/lexer.l"
return TUNNEL;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 "compilerNome/lexer.l"
return END_TUNNEL;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 "compilerNome/lexer.l"
return FUNNEL;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "compilerNome/lexer.l"
return END_FUNNEL;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "compilerNome/lexer.l"
return POLYLINE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "compilerNome/lexer.l"
return CIRCLE;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "compilerNome/lexer.l"
return END_CIRCLE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "compilerNome/lexer.l"
return TORUSKNOT;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 89 "compilerNome/lexer.l"
return END_TORUSKNOT;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "compilerNome/lexer.l"
return SCALE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "compilerNome/lexer.l"
return END_POLYLINE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "compilerNome/lexer.l"
return INSTANCE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "compilerNome/lexer.l"
return END_INSTANCE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "compilerNome/lexer.l"
return TRANSLATE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "compilerNome/lexer.l"
return ROTATE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "compilerNome/lexer.l"
return REVERSE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 97 "compilerNome/lexer.l"
return FOREGROUND;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "compilerNome/lexer.l"
return END_FOREGROUND;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 99 "compilerNome/lexer.l"
return BACKGROUND;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 100 "compilerNome/lexer.l"
return END_BACKGROUND;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 101 "compilerNome/lexer.l"
return INSIDEFACES;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 102 "compilerNome/lexer.l"
return END_INSIDEFACES;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 103 "compilerNome/lexer.l"
return OUTSIDEFACES;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 104 "compilerNome/lexer.l"
return END_OUTSIDEFACES;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 105 "compilerNome/lexer.l"
return OFFSETFACES;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 106 "compilerNome/lexer.l"
return END_OFFSETFACES;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 107 "compilerNome/lexer.l"
return MIRROR;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 108 "compilerNome/lexer.l"
return BEG_DELETE;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 109 "compilerNome/lexer.l"
return END_DELETE;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 110 "compilerNome/lexer.l"
return GROUP;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 111 "compilerNome/lexer.l"
return END_GROUP;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 112 "compilerNome/lexer.l"
return SUBDIVISION;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 113 "compilerNome/lexer.l"
return END_SUBDIVISION;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 114 "compilerNome/lexer.l"
return SUBDIVISIONS;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 115 "compilerNome/lexer.l"
return TYPE;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 116 "compilerNome/lexer.l"
return OBRACE;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 117 "compilerNome/lexer.l"
return EBRACE;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 118 "compilerNome/lexer.l"
return MERGE;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 119 "compilerNome/lexer.l"
return END_MERGE;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 120 "compilerNome/lexer.l"
return EPSILON;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 121 "compilerNome/lexer.l"
return SWEEP;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 122 "compilerNome/lexer.l"
return END_SWEEP;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 123 "compilerNome/lexer.l"
return PATH;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 124 "compilerNome/lexer.l"
return ENDPATH;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 125 "compilerNome/lexer.l"
return CROSSSECTION;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 126 "compilerNome/lexer.l"
return END_CROSSSECTION;
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 127 "compilerNome/lexer.l"
nomlval.string=strdup(nomtext); return SLIDEREXPRESSION;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 128 "compilerNome/lexer.l"
nomlval.string=strdup(nomtext); return VARIABLE;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 129 "compilerNome/lexer.l"
return OPARENTHESES;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 130 "compilerNome/lexer.l"
return EPARENTHESES;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MULTI_COMMENT):
case YY_STATE_EOF(LINE_COMMENT):
case YY_STATE_EOF(INSIDE_MACRO):
#line 131 "compilerNome/lexer.l"
if (numBegComments != 0){std::cout << "Error: Missing *) of multiline comment." << std::endl;} return 0;
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 132 "compilerNome/lexer.l"
/* ignore whitespace */;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 133 "compilerNome/lexer.l"
ECHO;
	YY_BREAK
#line 1871 "D:/Dev/nome/compilerNome/lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 517 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 517 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 516);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 133 "compilerNome/lexer.l"


int scanFromSessionFileContent(Session* s, const char* textBuffer, size_t textBufferSize)
{
	YY_BUFFER_STATE bufferState = nom_scan_bytes(textBuffer, textBufferSize);

	nomlineno = 1;
    nomcolumn = 0;

	int ret = nomparse(s);
	nom_delete_buffer(bufferState);
	return ret;
}

